### PR TITLE
Create supporters.md

### PR DESCRIPTION
**Pull request by chrishtr**
This adds a list of supporting organizations and individuals.

### CODE REVIEW

**Review by jgraham — CHANGES_REQUESTED** [review]
Can I request we change this to a process where organisations add themselves? I'd prefer for it to be totally clear that one org isn't claiming the participation of another without their explicit approval.

**Comment by chrishtr** [comment]
Done.

**Comment by chrishtr** [comment]
> Can I request we change this to a process where organisations add themselves? I'd prefer for it to be totally clear that one org isn't claiming the participation of another without their explicit approval.

Done.

**Review by jgraham — COMMENTED** [review]
Thanks!

**Comment by chrishtr** [comment]
Could you approve and merge? I don't have permissions for that.

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
@jensimmons @gsnedders would either of you like to send a PR for Apple?

@scottlow for Microsoft? 

@bkardell for Igalia?

@zcorpan for Bocoup?

**Pull request merged**
